# Generated by Django 3.0.1 on 2019-12-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=255)),
                ('movie_director', models.CharField(max_length=255)),
                ('release_date', models.IntegerField()),
                ('duration', models.DurationField()),
                ('description', models.TextField(null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('thumbnail', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketTypes',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('showtime_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('show_break', models.DurationField(default=0)),
                ('end_time', models.DateTimeField(null=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.Clients')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.Seats')),
                ('showtime_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.Showtime')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.TicketTypes')),
            ],
        ),
    ]
