# Generated by Django 3.0.1 on 2019-12-23 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='seat_id',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.Clients')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.Seats')),
                ('tickettype_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.TicketTypes')),
            ],
        ),
        migrations.AlterField(
            model_name='reservations',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.Ticket'),
        ),
    ]
