# Generated by Django 3.0.1 on 2019-12-28 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_auto_20191227_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='worker.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='showtime_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='worker.Showtime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showtime',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
