# Generated by Django 3.0.1 on 2019-12-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_auto_20191228_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.FloatField(),
        ),
    ]
