# Generated by Django 3.0.1 on 2019-12-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_auto_20191229_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
