# Generated by Django 3.0.1 on 2019-12-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0010_auto_20191229_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='row_number',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(null=True),
        ),
    ]
