# Generated by Django 3.0.1 on 2019-12-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0012_reservation_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='ticket_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.Ticket'),
        ),
    ]
