# Generated by Django 3.0.1 on 2019-12-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0013_auto_20191229_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='ticket_id',
            field=models.ManyToManyField(to='worker.Ticket'),
        ),
    ]
