# Generated by Django 3.0.1 on 2020-01-29 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0016_auto_20200114_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='showtime_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Showtime'),
        ),
    ]
