# Generated by Django 3.0.1 on 2020-02-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0019_auto_20200131_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='showtime_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='worker.Showtime'),
        ),
    ]
