# Generated by Django 3.0.1 on 2020-02-01 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0020_auto_20200201_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='showtime_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='worker.Showtime'),
        ),
    ]
