# Generated by Django 3.0.1 on 2020-02-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0021_auto_20200201_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
