# Generated by Django 3.0.1 on 2020-02-15 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0023_auto_20200208_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Movie'),
        ),
    ]
