# Generated by Django 3.0.1 on 2020-03-08 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0029_auto_20200308_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 16, 49, 43, 800216)),
        ),
    ]
