# Generated by Django 3.0.1 on 2020-03-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0032_auto_20200308_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_expire',
            field=models.DateTimeField(null=True),
        ),
    ]
