# Generated by Django 3.0.1 on 2020-03-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0036_auto_20200315_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_email',
            field=models.BooleanField(default=False),
        ),
    ]
