# Generated by Django 3.0.4 on 2020-03-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0038_tickettype_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.Movie'),
        ),
    ]
