# Generated by Django 3.0.4 on 2020-03-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0039_auto_20200321_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
