# Generated by Django 3.0.4 on 2020-04-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0047_auto_20200405_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
