# Generated by Django 3.0.4 on 2020-04-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0048_auto_20200405_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(default='', max_length=255, upload_to='images'),
        ),
    ]
