# Generated by Django 3.0.4 on 2020-04-11 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0050_auto_20200409_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
