# Generated by Django 3.0.1 on 2019-12-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0011_auto_20191229_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ticket_id',
            field=models.ManyToManyField(to='worker.Ticket'),
        ),
    ]
