# Generated by Django 3.0.1 on 2020-01-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0015_auto_20200114_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='end_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
