# Generated by Django 3.0.1 on 2020-01-31 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0018_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='showtime_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worker.Showtime'),
        ),
    ]
