# Generated by Django 3.0.1 on 2020-02-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0022_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
