# Generated by Django 3.0.1 on 2020-02-21 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0025_reservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.TextField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 20, 58, 29, 819072)),
        ),
    ]
