# Generated by Django 3.0.1 on 2020-03-08 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0030_auto_20200308_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_expire',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 18, 26, 53, 790134)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 17, 56, 53, 790134)),
        ),
    ]
