# Generated by Django 3.0.1 on 2020-03-08 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0031_auto_20200308_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 18, 18, 53, 428916)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_expire',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 8, 18, 48, 53, 428916)),
        ),
    ]
