# Generated by Django 3.0.1 on 2020-03-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0034_reservation_reservation_confirm_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_confirm_code',
            new_name='reservation_confirmation_code',
        ),
    ]
