# Generated by Django 3.0.1 on 2020-03-15 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0035_auto_20200308_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Client'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.Client'),
        ),
    ]
